### ISSUE TITLE
Please upgrade to python 3.7

### ISSUE THREAD

**Issue by shannog2** [bioexcel/biobb_pmx#4]
Hi,

I am a big fan of the biobb modules. This seems to be the only one requiring python 3.6.5 however. This causes issues when trying to create a Conda environment. It would be great if you could upgrade to bring it inline with the others please.

Many thanks

**Comment by PauAndrio** [comment]
Hi @shannog2 ,

We're glad to tell you that the biobb_pmx is already  published and it includes several new features including the Python 3.7 update.

Regards,
Biobb_team
